apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-prod-service
  namespace: prod
spec:
  type: NodePort
  selector:
    app: fastapi-app-prod
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30001  # Prod ortamında farklı bir NodePort belirledik
