apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-prod-service
spec:
  type: NodePort  # Burayı LoadBalancer'dan NodePort'a değiştirin
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31662  # Belirlediğiniz NodePort numarası
