apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app-prod
  template:
    metadata:
      labels:
        app: fastapi-app-prod
    spec:
      containers:
      - name: fastapi-app
        image: hanoguz00/fastapi-app:latest
        ports:
        - containerPort: 8002
