apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-test-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30002 # Minikube dışa açılan portu
  selector:
    app: fastapi-app-test

