apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-test-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: fastapi-app-test
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30002  # Test ortamında farklı bir NodePort belirledik
